name: PicoLowLevel CI

on:
  push:
    branches:
      - main


jobs:
        
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: refs/heads/main
    - name: Build code with arduino-cli and make
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
        arduino-cli lib install "Adafruit SH110X"
        arduino-cli --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json core update-index
        arduino-cli --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json core install rp2040:rp2040
        make -j4
    - name: Rename built files
      run: |
        mkdir upload
        mv bin/mod1/PicoLowLevel.ino.uf2 upload/mod1.uf2
        mv bin/mod2/PicoLowLevel.ino.uf2 upload/mod2.uf2
        mv bin/mod3/PicoLowLevel.ino.uf2 upload/mod3.uf2
        mv bin/mod1/PicoLowLevel.ino.bin upload/mod1.bin
        mv bin/mod2/PicoLowLevel.ino.bin upload/mod2.bin
        mv bin/mod3/PicoLowLevel.ino.bin upload/mod3.bin
    - uses: actions/upload-artifact@v3
      with:
        name: Built files
        path: upload