name: PicoLowLevel CI

on:
  push:
    branches:
      - main


jobs:
        
  build:
    name: Build

    strategy:
      matrix:
        libraries: ["Adafruit SH110X",]  
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install arduino-cli
      uses: arduino/setup-arduino-cli@v1
     
    - name: Install libraries
      run: |
        arduino-cli lib install "${{ matrix.libraries }}"
    
    - name: Install RP2040 core
      run: |
        arduino-cli --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json core update-index
        arduino-cli --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json core install rp2040:rp2040
    
    - name: Build
      run: |
        make -j4
    
    - name: Rename built files
      run: |
        mkdir upload
        mv bin/mod1/PicoLowLevel.ino.uf2 upload/mod1.uf2
        mv bin/mod2/PicoLowLevel.ino.uf2 upload/mod2.uf2
        mv bin/mod3/PicoLowLevel.ino.uf2 upload/mod3.uf2
        mv bin/mod1/PicoLowLevel.ino.bin upload/mod1.bin
        mv bin/mod2/PicoLowLevel.ino.bin upload/mod2.bin
        mv bin/mod3/PicoLowLevel.ino.bin upload/mod3.bin
    
    - uses: actions/upload-artifact@v3
      with:
        name: Built files
        path: upload